### ISSUE TITLE
New format in version 2.8.1 does not support loading from YAML files formatted from versions <2.8

### ISSUE THREAD

**Issue by davidallen353** [the-aerospace-corporation/gps_time#2]
Prior to version 2.8, the `GPSTime` class had attributes `week_number` and `time_of_week`. If stored in a YAML file, this would be stored as:
```yaml
!!python/object:gps_time.core.GPSTime
    time_of_week: 23234.2
    week_number: 213
```

In version 2.8.1, the `GPSTime` class was changes to have attributes of `week_number`, `seconds`, and `femtoseconds` with `time_of_week` becoming a property with a setter to ensure existing code still works. However, if a `GPSTime` object is created using a YAML file for an older version of this library, it will not be instantiated properly and will lack the `seconds` and `femtoseconds` attributes.
